export const discountProductsDetails = [
    { id: 213, description: "Appliances for your home | Up to 55% off", image: "https://www.electrolux.in/globalassets/electrolux-india/kitchen/refrigerators/eqe6879a-b/eqe6879a-b-fr-cl-1500x1500.png"},
    { id: 417, description: "Automotive essentials | Up to 60% off", image: "https://m.media-amazon.com/images/I/818bNc3MdDL._SY355_.jpg"},
    { id: 342, description: "Up to 70% off | Book store", image: "https://dkstatics-public.digikala.com/digikala-products/8681dfafe54ddd24b39df6458c86d2f3b37059f2_1608219576.jpg?x-oss-process=image/resize,m_lfit,h_800,w_800/quality,q_90"},
    { id: 657, description: "Up to 60% off | Styles for men", image: "https://cdn.shopify.com/s/files/1/0527/8230/1340/products/5905P_001_1_800x.jpg?v=1627404093"},
    { id: 803, description: "Up to 70% off | Gaming Laptops & Accessories", image: "https://m.media-amazon.com/images/I/71--IQUHVwL._SL1500_.jpg"},
]

export const purchaseProductsDetails = [
  {
    id: 123,
    description: "OnePlus 10 Pro 5G (Emerald Forest, 8GB RAM, 128GB Storage)",
    price: 622.5,
    rating: 4,
    image: "https://m.media-amazon.com/images/I/618hqM-yxtL._SX679_.jpg",
    image2: "https://m.media-amazon.com/images/I/51kFb5UvwkL._SX679_.jpg",
    features: [
      "Camera: 48MP Main Camera with Sony IMX 789 Lens (OIS enabled), 50MP Ultra-wide angle camera & 8MP Tele photo lens; Front (Selfie) Camera: 32MP; Flash: Dual LED",
      "Camera Features: Hasselblad Camera for Mobile, Nightscape, Ultra HDR, Smart Scene Recognition, Portrait Mode, Pro Mode, Panorama Mode, Tilt-Shift mode, Long Exposure Mode, 150° Wide angle Mode, Dual-View Video, Movie Mode, Xpan Mode, Filters, Super Stable, Video Nightscape, Video HDR, Video Portrait, Focus Tracking, Timelapse",
      "Display: 6.7 Inches; 120 Hz QHD+ Fluid AMOLED with LTPO; Resolution: 3216 x 1440; Aspect Ratio: 20:9",
      "Display Features: Nature tone display, Video colour enhancer, Colour personalization, Colour vision enhancement, Auto brightness, Manual brightness, Screen colour temperature, Bright HDR video mode, Night Mode, Multi-brightness colour calibration, Vibrant Colour Effect Pro, Ultra high resolution video",
      "Operating System: Oxygen OS based on Android 12. Processor: Qualcomm Snapdragon 8 Gen 1",
      "Battery & Charging: 5000 mAh with 80W SuperVOOC. In-Display Fingerprint Sensor",
      "Alexa Hands-Free capable: Download the Alexa app to use Alexa hands-free. Play music, make calls, hear news, open apps, navigate, and more, all using just your voice, while on-the-go.",
      "Connector type: usb type c, Cellular technology:5g, 4g lte, Operating system:oxygenos, Form factor:smartphone",
    ],
  },
  {
    id: 987,
    description:
      "Safari Pentagon Trolley Bag Set, Small and Medium Suitcase for Travel",
    price: 249,
    rating: 4,
    image: "https://m.media-amazon.com/images/I/610-qE6QuRL._UX569_.jpg",
    image2: "https://m.media-amazon.com/images/I/71Hk2GhVRYL._UX569_.jpg",
    features: [
      "PREMIUM QUALITY: Pentagon is a scratch and impact resistant, light weight yet durable suitcase made of polypropylene. This water resistant high quality trendy hard case trolley bag makes travelling comfortable",
      "DIMENSIONS : Our stylish yet spacious two compartment textured luggage comes in dimension - S-55cms x 38cms x 23cms & M-66cms x 47 cms x 28cms. It has a capacity of S-48L & M-87L .Provided with spacious divider compartment to hold all necessary things while travelling.",
      "FEATURES & STYLE: Our 4 Wheel Red Trolley bag comes with a Number Lock. We provide you a smooth adjustable handle for easy movement of the Trolley. Our small & medium size check in suitcase are a perfect combo for all your travel",
      "Style: Show off with our trendy yet comfortable travel suitcase with 360 degree easy manoeuvrable wheels. Explore the world with our multifunctional suitcase",
      "3 YEAR WARRANTY: All our bags are MADE IN INDIA and come with a 3-year International Warranty against manufacturing defects",
    ],
  },
  {
    id: 456,
    description:
      "OnePlus Buds Pro Bluetooth Truly Wireless in Ear Earbuds with mic",
    price: 159.99,
    rating: 4,
    image: "https://m.media-amazon.com/images/I/51jJs-kCh6S._SX679_.jpg",
    image2: "https://m.media-amazon.com/images/I/61dkhl0BNmS._SX679_.jpg",
    features: [
      "Smart Adaptive Noise Cancellation: Up to 40 dB hybrid noise cancelling with automated environmental noise detection & adjustment.",
      "OnePlus Audio ID: Personalize your audio via simple listening test at first time setup. This unique hearing profile ID allows one to enjoy the most optimal listening experience best suited to him or her by compensating for mild hearing loss and related aural deficiencies.",
      "Worry-free Battery Life: Enjoy up to 38 hours of music and a quick Warp Charging of 10 minutes for 10 hours of playtime.",
      "Full charged earbud: up to 5h(music playback; ANC ON); up to 7h(music playback; ANC Off) Full charged earbud: 3.5h(phone call)",
      "Powerful, Punchy Bass: Drop the bass with dual 11mm dynamic drivers, delivering a precisely boosted sound profile designed to move you.",
      "Zen Mode Air: 5 presets of white noise can be played alongside adaptive noise cancellation - eg. Meditation, Summers, Seashore, Night-time camping etc. Now keep calm, relax and stay focus.",
      "Seamless connectivity: Instantaneous pairing with OnePlus smartphone, as soon as you open the charging case lid.",
    ],
  },
  {
    id: 789,
    description: "ASUS TUF Gaming A15, 15.6-inch FHD 144Hz, AMD Ryzen 5 4600H",
    price: 745.99,
    rating: 4,
    image: "https://m.media-amazon.com/images/I/41LDfnScXZS._SX300_SY300_QL70_FMwebp_.jpg",
    image2: "https://m.media-amazon.com/images/I/81x9vxrPFwS._SX679_.jpg",
    features: [
      "Processor: AMD Ryzen 5 4600H Mobile Processor (6-core/12-thread, 11MB Cache, 4.0 GHz max boost)",
      "Play over 100 high-quality PC games, plus new and upcoming blockbusters on day one like Halo Infinite, Forza Horizon 5, and Age of Empires IV with your new FA506IHRZ-HN111W and one month of Game Pass-including EA Play.",
      "With new games added all the time, there’s always something new to play. Age of Empires IV, Back 4 Blood, Battlefield V, Forza Horizon 5, Halo Infinite*, Knockout City, Microsoft Flight Simulator, Minecraft PC Bundle, Need for Speed Heat, Psychonauts2, The Sims 4, Titanfall 2, 12 Minutes",
      "Memory: 16GB SO-DIMM (8GB x 2) DDR4-3200MHz Support up to 32GB with | Storage: 512GB PCIe 3.0 NVMe M.2 SSD with additional empty 1x M.2 Slot for storage upgrade",
      "Graphics: NVIDIA GeForce GTX 1650 GDDR6 4GB VRAM with Optimus",
      "Operating System: Pre-installed Windows 11 Home with Lifetime Validity | Software Included: 1-month trial for new Microsoft 365 customers.",
      "Keyboard: 1-Zone RGB Backlit Chiclet Keyboard",
    ],
  },
  {
    id: 135,
    description:
      "Quaker Oats 2kg | Rolled Oats | 100% Natural Wholegrain | Easy to Cook",
    price: 25.83,
    rating: 5,
    image: "https://m.media-amazon.com/images/I/61SHF0RYZDL._SX679_.jpg",
    image2: "https://m.media-amazon.com/images/I/71l-dpxk+oL._SX679_.jpg",
    features: [
      "Lasting Energy : Start the day with a bowlful of nutritious & tasty Quaker Oats. These 100% Natural Wholegrain Oats have complex carbohydrates that breaks down slowly to provide energy that lasts.",
      "Helps reduce cholestrol : As part of a diet low in saturated fat, sodium and cholesterol, alongwith a healthy & active lifestyle, consumption of 2 bowls of Oats everyday giving 3g soluble fiber Beta glucan may help reduce cholesterol.",
      "Helps Maintain Weight: Make it a part of fitness and weight loss journey",
      "100% Natural Wholegrain Oats : Rolled oats in your choice of pack size Oats 1kg, Oats 2kg, Oats 1.5kg",
      "Easy to Cook : Ready in just 3 minutes. Quaker Oats can be eaten sweet or savoury or add them as a wholesome ingredient in your favorite dishes, such as Idli or Poha or Masala Oats or whip some classic oatmeal cookies. Enjoy the wholesome benefits of this whole grain in any number of meals or snacks, any time of day.",
      "Rich in Fiber & Source of Protein",
      "Container type: Bag",
    ],
  },
  {
    id: 167,
    description: "Nike Mens Air Max Impact 4 Running Shoe | Lace-Up",
    price: 121.25,
    rating: 4,
    image: "https://res.cloudinary.com/sport2000-images/image/upload/c_pad,f_auto,h_500,q_auto,w_500/nike_dm1124_006_detail3_to8rel.jpg",
    image2: "https://static.nike.com/a/images/t_default/f3b760d7-2c28-4801-bec6-12c32d7137b1/air-max-impact-4-basketball-shoes-CcJxBx.png",
    features: [
      "Closure: Lace-Up Cushioned Comfort",
      "Shoe Width: Medium",
      "A Max Air unit in the heel provides cushioning where it's needed. Padding in the heel and tongue adds to the soft feel.",
      "Durable Traction",
      "Herringbone traction on the outsole helps control your movement and hold your ground. Diamond-shaped cut-outs expose the foam and help reduce weight. Toe skin adds durability.",
      "Full-Foot Security",
      "The sculpted foam midsole swoops up on either side of your heel to help keep it stable. Moulded rubber wings do the same in the forefoot.",
    ],
  },
];

export const SearchCategories = [
    { value: "all", category: "All"},
    { value: "alexa-skills", category: "Alexa Skills"},
    { value: "amazon-devices", category: "Amazon Devices"},
    { value: "fashion", category: "Amazon Fashion"},
    { value: "nowstore", category: "Amazon Fresh"},
    { value: "amazon-pharmacy", category: "Amazon Pharmacy"},
    { value: "appliances", category: "Appliances"},
    { value: "mobile-apps", category: "Apps & Games"},
    { value: "baby", category: "Baby"},
    { value: "beauty", category: "Beauty"},
    { value: "stripbooks", category: "Books"},
    { value: "automotive", category: "Car & Motorbike"},
    { value: "apparel", category: "Clothing & Accessories"},
    { value: "collectibles", category: "Collectibles"},
    { value: "computers", category: "Computers & Accessories"},
    { value: "electronics", category: "Electronics"},
    { value: "furniture", category: "Furniture"},
    { value: "lawngarden", category: "Garden & Outdoors"},
    { value: "gift-cards", category: "Gift Cards"},
    { value: "grocery", category: "Grocery & Gourmet Foods"},
    { value: "hpc", category: "Health & Personal Care"},
    { value: "kitchen", category: "Home & Kitchen"},
    { value: "industrial", category: "Industrial & Scientific"},
    { value: "jewelry", category: "Jewellery"},
    { value: "digital-text", category: "Kindle Store"},
    { value: "luggage", category: "Luggage & Bags"},
    { value: "luxury-beauty", category: "Luxury Beauty"},
    { value: "dvd", category: "Movies & TV Shows"},
    { value: "popular", category: "Music"},
    { value: "mi", category: "Musical Instruments"},
    { value: "office-products", category: "Office Products"},
    { value: "pets", category: "Pet Supplies"},
    { value: "instant-video", category: "Prime Video"},
    { value: "shoes", category: "Shoes & Handbags"},
    { value: "software", category: "Software"},
    { value: "sporting", category: "Sports, Fitness & Outdoors"},
    { value: "specialty-aps-sns", category: "Subscribe & Save"},
    { value: "home-improvement", category: "Tools & Home Improvement"},
    { value: "toys", category: "Toys & Games"},
    { value: "under-ten-dollars", category: "Under ₹500"},
    { value: "videogames", category: "Video Games"},
    { value: "watches", category: "Watches"}
]